version: '2.3'

services:
    bjj-server:
        restart: always
        build: ./
        command: python app.py
        scale: 1
        depends_on:
            - bjj-rabbit
        ports:
            - "58095:58095"

    uaejjf-events-task:
        restart: always
        build: ./
        command: python uaejjf_events_task.py
        scale: 1
        depends_on:
            - bjj-rabbit

    uaejjf-event-result:
        restart: on-failure
        build: ./
        command: python uaejjf_event_result.py
        scale: 2
        depends_on:
            - bjj-rabbit
    
    uaejjf-event-info:
        restart: on-failure
        build: ./
        command: python uaejjf_event_info.py
        scale: 2
        depends_on:
            - bjj-rabbit

    uaejjf-profile-info:
        restart: on-failure
        build: ./
        command: python uaejjf_profile_info.py
        scale: 2
        depends_on:
            - bjj-rabbit
    
    smoothcomp-events-task:
        restart: always
        build: ./
        command: python smoothcomp_events_task.py
        scale: 1
        depends_on:
            - bjj-rabbit

    smoothcomp-event-result:
        restart: on-failure
        build: ./
        command: python smoothcomp_event_result.py
        scale: 2
        depends_on:
            - bjj-rabbit
    
    smoothcomp-event-info:
        restart: on-failure
        build: ./
        command: python smoothcomp_event_info.py
        scale: 2
        depends_on:
            - bjj-rabbit

    smoothcomp-profile-info:
        restart: on-failure
        build: ./
        command: python smoothcomp_profile_info.py
        scale: 2
        depends_on:
            - bjj-rabbit

    bjj-rabbit:
        restart: always
        image: rabbitmq:3-management
        volumes:
          - /opt/rabbitdata/bjj:/var/lib/rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=rabbitmq
          - RABBITMQ_DEFAULT_PASS=rabbitmq
          - RABBITMQ_HOST=/
          - RABBITMQ_PORT=5672
          - RABBITMQ_HEARTBEAT=0
        ports:
          - "11900:5672"
          - "11901:15672"
